title: Jeppe.design
author:
  name: Jesper Andersson
  email: jsprA86@gmail.com
baseurl: ""
encoding: "utf-8"
markdown: kramdown
excleude: ['README.md']
permalink: pretty
excerpt_separator: <!--more-->
sass:
  sass_dir: styles/_sass
  style: compressed
